# Generated by Django 5.2 on 2025-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='google_maps_api_key',
            field=models.CharField(blank=True, help_text='API Key de Google Maps', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_actividades_bg',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección de actividades', null=True, upload_to='site'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_hero_1',
            field=models.ImageField(blank=True, help_text='Primera imagen del carousel principal', null=True, upload_to='site/hero'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_hero_2',
            field=models.ImageField(blank=True, help_text='Segunda imagen del carousel principal', null=True, upload_to='site/hero'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_hero_3',
            field=models.ImageField(blank=True, help_text='Tercera imagen del carousel principal', null=True, upload_to='site/hero'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_hero_4',
            field=models.ImageField(blank=True, help_text='Cuarta imagen del carousel principal', null=True, upload_to='site/hero'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_actividades',
            field=models.CharField(blank=True, default='Descubre transporte, artesanías y actividades físicas únicas', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_hero_1',
            field=models.CharField(blank=True, default='Descubre la magia del Huila', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_hero_2',
            field=models.CharField(blank=True, default='Vive experiencias únicas', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_hero_3',
            field=models.CharField(blank=True, default='Conecta con la naturaleza', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='subtitulo_hero_4',
            field=models.CharField(blank=True, default='Vive la aventura', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_actividades',
            field=models.CharField(blank=True, default='ACTIVIDADES PARA TODOS', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_hero_1',
            field=models.CharField(blank=True, default='Bienvenido a Garzón', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_hero_2',
            field=models.CharField(blank=True, default='Cultura y Tradición', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_hero_3',
            field=models.CharField(blank=True, default='Naturaleza Exuberante', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='titulo_hero_4',
            field=models.CharField(blank=True, default='Aventura y Adrenalina', max_length=200),
        ),
    ]
