# Generated by Django 5.2 on 2025-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsitio_google_maps_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='mapa_tipo_inicial',
            field=models.CharField(choices=[('roadmap', 'Mapa de carreteras'), ('satellite', 'Satelital'), ('hybrid', 'Híbrido'), ('terrain', 'Terreno')], default='satellite', help_text='Tipo de mapa inicial', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mapa_zoom_inicial',
            field=models.PositiveSmallIntegerField(default=14, help_text='Nivel de zoom inicial del mapa'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_activo',
            field=models.BooleanField(default=False, help_text='Activar modal al cargar la página'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_boton_accion_texto',
            field=models.CharField(blank=True, help_text='Texto para botón de acción', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_boton_texto',
            field=models.CharField(blank=True, default='Entendido', help_text='Texto del botón de cierre', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_contenido',
            field=models.TextField(blank=True, help_text='Contenido del modal (HTML permitido)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_imagen',
            field=models.ImageField(blank=True, help_text='Imagen para el modal', null=True, upload_to='site/modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_titulo',
            field=models.CharField(blank=True, help_text='Título del modal', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_url_boton',
            field=models.URLField(blank=True, help_text='URL para botón de acción opcional', null=True),
        ),
    ]
