# Generated by Django 5.2 on 2025-07-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsitio_mapa_tipo_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='google_maps_api_key',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='imagen_actividades_bg',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='imagen_hero_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='imagen_hero_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='imagen_hero_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='imagen_hero_4',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='mapa_tipo_inicial',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='mapa_zoom_inicial',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_activo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_boton_accion_texto',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_boton_texto',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_contenido',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_imagen',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_titulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='modal_url_boton',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='subtitulo_actividades',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='subtitulo_hero_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='subtitulo_hero_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='subtitulo_hero_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='subtitulo_hero_4',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='titulo_actividades',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='titulo_hero_1',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='titulo_hero_2',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='titulo_hero_3',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='titulo_hero_4',
        ),
    ]
