# Generated by Django 5.2 on 2025-04-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(choices=[('hotel', 'Hotel'), ('restaurante', 'Restaurante'), ('cafe', 'Café'), ('bar', 'Bar'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='establecimientos')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('rango_precios', models.CharField(choices=[('$', 'Económico'), ('$$', 'Moderado'), ('$$$', 'Costoso')], default='$$', max_length=3)),
                ('servicios', models.TextField(blank=True, help_text='Servicios ofrecidos separados por comas')),
                ('horario', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('destacado', models.BooleanField(default=False)),
                ('organizador', models.CharField(blank=True, max_length=200)),
                ('contacto', models.TextField(blank=True)),
                ('programa', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('distancia', models.DecimalField(decimal_places=2, help_text='Distancia en kilómetros', max_digits=5)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('recomendaciones', models.TextField(blank=True)),
                ('imagen_principal', models.ImageField(upload_to='rutas')),
                ('mapa_ruta', models.JSONField(blank=True, help_text='Coordenadas del trazado para Google Maps', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=255)),
                ('imagen_principal', models.ImageField(upload_to='lugares')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('horario', models.TextField(blank=True)),
                ('costo_entrada', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='turismo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Lugares Turísticos',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='lugares/galerias')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('es_portada', models.BooleanField(default=False)),
                ('lugar_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='turismo.lugarturistico')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(help_text='Posición en la secuencia de la ruta')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tiempo_estancia', models.CharField(blank=True, help_text='Tiempo recomendado de parada', max_length=50)),
                ('lugar_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_ruta', to='turismo.lugarturistico')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='turismo.ruta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
    ]
