# Generated by Django 5.2 on 2025-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='imagen',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización'),
        ),
    ]
