# Generated by Django 5.2 on 2025-07-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alter_imagen_options_imagen_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo_actividad', models.CharField(choices=[('senderismo', 'Senderismo'), ('escalada', 'Escalada'), ('ciclismo', 'Ciclismo'), ('natacion', 'Natación'), ('kayak', 'Kayak'), ('rafting', 'Rafting'), ('parapente', 'Parapente'), ('cabalgata', 'Cabalgata'), ('canopy', 'Canopy'), ('rappel', 'Rappel'), ('camping', 'Camping'), ('avistamiento', 'Avistamiento de Aves'), ('otro', 'Otra')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('dificultad', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='principiante', max_length=15)),
                ('duracion', models.CharField(help_text="Ej: '2 horas', 'Día completo'", max_length=50)),
                ('costo', models.CharField(blank=True, max_length=100)),
                ('edad_minima', models.PositiveSmallIntegerField(default=0, help_text='Edad mínima recomendada')),
                ('capacidad_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('equipamiento_incluido', models.TextField(blank=True, help_text='Equipamiento proporcionado')),
                ('equipamiento_requerido', models.TextField(blank=True, help_text='Equipamiento que debe traer el participante')),
                ('recomendaciones_salud', models.TextField(blank=True)),
                ('mejor_epoca', models.CharField(blank=True, help_text='Mejor época del año para la actividad', max_length=200)),
                ('horarios_disponibles', models.TextField(blank=True)),
                ('instructor_guia', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagen_principal', models.ImageField(upload_to='actividades_fisicas')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades Físicas',
            },
        ),
        migrations.CreateModel(
            name='Artesania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categoria', models.CharField(choices=[('ceramica', 'Cerámica'), ('textil', 'Textil'), ('madera', 'Madera'), ('cuero', 'Cuero'), ('metal', 'Metal'), ('piedra', 'Piedra'), ('fibra', 'Fibra Natural'), ('joyeria', 'Joyería'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('artesano', models.CharField(help_text='Nombre del artesano o taller', max_length=200)),
                ('lugar_origen', models.CharField(max_length=255)),
                ('tecnica_elaboracion', models.TextField(blank=True)),
                ('materiales', models.TextField(help_text='Materiales utilizados separados por comas')),
                ('precio_referencia', models.CharField(blank=True, max_length=100)),
                ('tiempo_elaboracion', models.CharField(blank=True, max_length=100)),
                ('imagen_principal', models.ImageField(upload_to='artesanias')),
                ('destacado', models.BooleanField(default=False)),
                ('disponible_venta', models.BooleanField(default=True)),
                ('contacto_artesano', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True, help_text='Historia o tradición detrás de la artesanía')),
            ],
            options={
                'verbose_name_plural': 'Artesanías',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tipo', models.CharField(choices=[('bus', 'Autobús'), ('taxi', 'Taxi'), ('moto', 'Mototaxi'), ('bicicleta', 'Bicicleta'), ('caminata', 'Caminata'), ('vehiculo_propio', 'Vehículo Propio'), ('tour', 'Tour Organizado'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('duracion_estimada', models.CharField(help_text="Ej: '30 minutos', '2 horas'", max_length=50)),
                ('costo_aproximado', models.CharField(blank=True, max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horarios', models.TextField(blank=True, help_text='Horarios de operación')),
                ('recomendaciones', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='transporte')),
                ('destacado', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Transportes',
            },
        ),
        migrations.CreateModel(
            name='ImagenActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='actividades_fisicas/galerias')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='turismo.actividadfisica')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImagenArtesania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='artesanias/galerias')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
                ('artesania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='turismo.artesania')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
