# Generated by Django 5.2 on 2025-08-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_actividadfisica_artesania_transporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-hiking)', max_length=50)),
                ('color_tema', models.CharField(blank=True, help_text='Color hexadecimal para esta categoría', max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría de Actividad Física',
                'verbose_name_plural': 'Categorías de Actividades Físicas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaArtesania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-pottery)', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría de Artesanía',
                'verbose_name_plural': 'Categorías de Artesanías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='puntoruta',
            options={'ordering': ['orden'], 'verbose_name': 'Punto de Ruta', 'verbose_name_plural': 'Puntos de Ruta'},
        ),
        migrations.RemoveField(
            model_name='actividadfisica',
            name='tipo_actividad',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='mapa_ruta',
        ),
        migrations.AddField(
            model_name='actividadfisica',
            name='disponible_todo_año',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actividadfisica',
            name='nivel_riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', help_text='Nivel de riesgo de la actividad', max_length=20),
        ),
        migrations.AddField(
            model_name='actividadfisica',
            name='requiere_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='color_marcador',
            field=models.CharField(blank=True, help_text='Color hexadecimal del marcador (ej: #FF0000)', max_length=7),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='icono_personalizado',
            field=models.CharField(blank=True, help_text='Nombre del icono personalizado para este punto', max_length=50),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='mostrar_en_mapa',
            field=models.BooleanField(default=True, help_text='Si está marcado, este punto se mostrará en el mapa'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='mapa_configuracion',
            field=models.JSONField(blank=True, help_text='Configuración específica del mapa (centro, zoom, estilo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud en formato decimal', null=True),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud en formato decimal', null=True),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='latitud',
            field=models.FloatField(help_text='Latitud en formato decimal'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='longitud',
            field=models.FloatField(help_text='Longitud en formato decimal'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='tiempo_estancia',
            field=models.CharField(blank=True, help_text="Tiempo recomendado de parada (ej: '30 min', '2 horas')", max_length=50),
        ),
        migrations.AddField(
            model_name='actividadfisica',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='turismo.categoriaactividadfisica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artesania',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artesanias', to='turismo.categoriaartesania'),
        ),
    ]
