# Generated by Django 5.2 on 2025-09-20 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0004_categoriaactividadfisica_categoriaartesania_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: ph-mountains)', max_length=50)),
                ('color_tema', models.CharField(blank=True, help_text='Color hexadecimal para esta categoría (ej: #FF5733)', max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Fotografía',
                'verbose_name_plural': 'Categorías de Fotografías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TagFotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Fotografía',
                'verbose_name_plural': 'Etiquetas de Fotografías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(help_text='Imagen principal de la fotografía', upload_to='galeria/')),
                ('fotografo', models.CharField(blank=True, help_text='Nombre del fotógrafo', max_length=200)),
                ('fecha_captura', models.DateField(blank=True, help_text='Fecha en que se tomó la fotografía', null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación donde se tomó la foto', max_length=255)),
                ('camara', models.CharField(blank=True, max_length=100)),
                ('lente', models.CharField(blank=True, max_length=100)),
                ('iso', models.CharField(blank=True, max_length=50)),
                ('apertura', models.CharField(blank=True, max_length=50)),
                ('velocidad', models.CharField(blank=True, max_length=50)),
                ('destacada', models.BooleanField(default=False, help_text='Marcar si es una fotografía destacada')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='turismo.categoriafotografia')),
                ('lugar_relacionado', models.ForeignKey(blank=True, help_text='Lugar turístico relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografias_galeria', to='turismo.lugarturistico')),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['-destacada', 'orden', '-created'],
            },
        ),
        migrations.CreateModel(
            name='FavoritesFotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fotografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.fotografia')),
            ],
            options={
                'verbose_name': 'Fotografía Favorita',
                'verbose_name_plural': 'Fotografías Favoritas',
                'unique_together': {('fotografia', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='FotografiaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='turismo.fotografia')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='turismo.tagfotografia')),
            ],
            options={
                'unique_together': {('fotografia', 'tag')},
            },
        ),
    ]
